### ISSUE TITLE
filtering on multiple columns fails when Redis backend is R/O

### ISSUE THREAD

**Issue by ebirger** [josiahcarlson/rom#104]
Issuing a query with multiple fields in its filter() fails when the Redis backend is R/O (slave)

Issue seems to stem from the use of ZUNIONSTORE.

Would it be possible to provide R/O access to rom models?

**Comment by josiahcarlson** [comment]
To make this work, I would need to re-implement all of Redis including Lua scripting (which is how most of indexing and search has been using in Rom for a few years now), in Python. That is out of scope. I'm sorry.

Did you know that you can enable slave writes? Yep. https://github.com/antirez/redis/blob/unstable/redis.conf#L317

**Comment by ebirger** [comment]
Fair enough.

Queries requiring write permissions caught me by surprise, that's all. But I understand your reasoning.

I did notice that slave writes were optionally possible, but did not research the effects of enabling that feature when working with rom.

Thanks!

**Comment by josiahcarlson** [comment]
You'll want to be careful in the context of `.save()` or `session.commit()` if you do enable slave writes, as they would write to the slave if you had slave writes enabled. That may cause some data consistency issues between different master/slave instances, but it shouldn't crash rom.

**Comment by ebirger** [comment]
Thanks for the tip. I'll look into this and other alternatives to circumvent this issue.

Kudos on an excellent project!
