### ISSUE TITLE
Refresh on new session fails

### ISSUE THREAD

**Issue by peter-conalgo** [josiahcarlson/rom#107]
```python
Python 3.6.0 (default, Mar  4 2017, 12:32:37) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import rom
>>> rom.session.refresh_all()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../ENV/lib/python3.6/site-packages/rom/util.py", line 592, in refresh_all
    self.refresh(*self.known.values(), force=kwargs.get('force'))
AttributeError: 'Session' object has no attribute 'known'
>>> 
```

I think there are some other code paths that will hit a missing `known` attribute as well.

**Comment by josiahcarlson** [comment]
Only cases where the object wouldn't have been initialized is if the first thing that was called was `.refresh()` or `.refresh_all()`. Since `.refresh_all()` calls `.refresh()`, the solution is a single addition of `self._init()` in `.refresh()`.

This should now be fixed in version 0.38.1

**Comment by peter-conalgo** [comment]
Not sure if this is a related issue, and I am still on 0.38.0:

```python
>>> a=Invoice()
>>> a.save()
17
>>> a.delete()
>>> rom.session.refresh()
>>> rom.session.refresh(1)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/peter/opendime/website/ENV/lib/python3.6/site-packages/rom/util.py", line 578, in refresh
    o,))
rom.exceptions.ORMError: Cannot refresh an object that is not an instance of a Model (you provided 1)
>>>

**Comment by josiahcarlson** [comment]
Have you read what refresh does? It refreshes the data on the model from the database. Not providing anything will not refresh anything (https://github.com/josiahcarlson/rom/blob/master/rom/util.py#L550) and providing something that isn't an instance of a Model (or a list or tuple thereof), will raise that exception.

**Comment by peter-conalgo** [comment]
Sorry, my example was wrong. I meant to write `rom.session.refresh(force=1)` but that works just fine and doesn't demonstrate the issue I though I was showing. I will contemplate my code more... and probably just write my own sessions to do what's appropriate for my case.

**Comment by josiahcarlson** [comment]
The point of the rom session is to do one of 2 things:
1. Act as a session store like a standard database session provided by Django ORM, SQLAlchemy, etc., minus the transaction stuff (obviously) - in this case, caching entities in the context of a single web request, offering a single place to "save all your changes" or "discard all your changes".
2. A null session store; which doesn't keep a list of entities, and relies on you to manually save/rollback yourself: https://github.com/josiahcarlson/rom/blob/master/rom/util.py#L56

**Comment by josiahcarlson** [comment]
Closing because the underlying bug is done, now it is just remaining for you to pick a session to use.
