### ISSUE TITLE
Query.like matches against id column

### ISSUE THREAD

**Issue by peter-conalgo** [josiahcarlson/rom#110]
I found this issue while putting numbers through suffix matching:

```python
class BugCheck(rom.Model):
    email = rom.Text(keygen=rom.IDENTITY_CI, index=True, prefix=True, suffix=True, default='')

>>> BugCheck(email='abc@gmail.com').save()
2
>>> BugCheck(email='abc@example.com').save()
2
>>> BugCheck.query.like(email='*2').all()
[<models.BugCheck object at 0x103c69240>]
>>> BugCheck.query.like(email='*4').all()
[]
```

Seems like the PK was considered as a match on email field.

**Comment by josiahcarlson** [comment]
I think you're right. I'll try to get to fixing that this coming week.

**Comment by josiahcarlson** [comment]
Okay, I have a very simple patch for this, will merge and deploy later today. Thank you Peter :)

**Comment by josiahcarlson** [comment]
Fixed in 0.39.4 . Thank you for the bug report.

**Comment by peter-conalgo** [comment]
Great! I'll check it out once on Pypi.

**Comment by josiahcarlson** [comment]
PyPI changed it's API, had to fix the makefile. Should now be available.
