### ISSUE TITLE
Cannot pass primary key on object creation

### ISSUE THREAD

**Issue by AndrewBurdyug** [josiahcarlson/rom#112]
Hi! 

I tried to populate my local instance of Redis and got such error: 

```python 
class User(rom.Model):
    id = rom.PrimaryKey()
    email = rom.String(required=True, unique=True)
```

```python 
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    obj = model(**item)
  File "/home/buran/envs/okapi/lib/python3.6/site-packages/rom/model.py", line 233, in __init__
    raise InvalidColumnValue("Cannot pass primary key on object creation")
rom.exceptions.InvalidColumnValue: Cannot pass primary key on object creation
```

Why I can't used id in object creation? I have data with ID's and Email's and just want to populate redis with exactly such IDs.

**Comment by josiahcarlson** [comment]
By default, rom's primary keys are not able to be overridden. They can be thought of as a Postgres-style OID that you can't get rid of.

```
class User(rom.Model):
    oid = rom.PrimaryKey()
    id = rom.Integer(required=True, unique=True)
    email = rom.String(required=True, unique=True)
```

The above will allow you to set the `id` and `email` attributes as you want (subject to uniqueness constraints), with the non-settable rom-side primary key being separated.

I previously discussed all of the what/why here: https://github.com/josiahcarlson/rom/issues/59

Closing.
