### ISSUE TITLE
Using rom.Model as mixin

### ISSUE THREAD

**Issue by thedamnedrhino** [josiahcarlson/rom#120]
Hi, I'm trying to decouple my business logic from the persistence layer code. So I've implemented my model classes without extending the `rom.Model` class. Naturally I can't persist these objects using this library. Now I'm creating separate "persisted" model classes, extending the original model classes that should add the persistence logic to it. Now if I want to persist them using this library I'd also have to include the `rom.Model` class as a mixin. So I was wondering if the persistence and mapping functionalities still work when used this way.

p.s: thank you for the great library :)

**Comment by thedamnedrhino** [comment]
I figured it out, but there are some pitfalls. *the `__init__` method of the `rom.Model` must be called*. If the `__init__`  method of the child class is to be overridden - this is certainly the case if the `__init__` method of the parent class (the main parent class and not `rom.Model`) is to be called, then `rom.Model.__init__` *must be called before any persisted properties are set in the main parent's `__init__`*.  Also, *the child class\` `__init__` can not have any mandatory arguments. e.g:

```
class Base():
  def __init__(self, p1):
    self.p1

class Child(Base, rom.Model):
  p1 = rom.TextField()
  p2 = rom.TextField() # additional properties can be defined
  def __init__(self, p1='a', **kwargs):
    rom.Model.__init__(self, p1=p1)
    Base.__init__(self, p1)
```

Please mention if there is anything else is to be noted.

**Comment by josiahcarlson** [comment]
If it works as a mixin, in any way, that is entirely accidental / coincidental. I didn't intend or design for it to work specifically in that scenario.

That said, yeah, you need to execute the `Model.__init__` method with all of the standard object creation mechanisms. That is pretty standard subclassing behavior, and is necessary for rom to do it's business (an entity should only exist in the rom world if it is created by the user explicitly via `MyModelSubclass(...)` or from the materialization as a result of a query - partial initializations aren't considered valid).
