### ISSUE TITLE
AttributeError: 'Session' object has no attribute 'known'

### ISSUE THREAD

**Issue by cdessez** [josiahcarlson/rom#123]
Hi,

After upgrading to version 0.42.0, my rom queries regularly crash with the following stacktrace:

```python
    return query.all()
  File "/usr/local/lib/python3.6/site-packages/rom/query.py", line 688, in all
    return self.execute()
  File "/usr/local/lib/python3.6/site-packages/rom/query.py", line 682, in execute
    return list(self)
  File "/usr/local/lib/python3.6/site-packages/rom/query.py", line 488, in _iter_results
    isk = set(session.known.keys())
  File "/usr/local/lib/python3.6/site-packages/eventlet/corolocal.py", line 45, in __getattribute__
    return object.__getattribute__(self, attr)
AttributeError: 'Session' object has no attribute 'known'
```

Looking at what changed in 1dade8515f5efd5415f6e5e9e0f6bb1e5136694a it seems like it uncovers a bug that was already there previously with the attribute `known` of the class `rom.util.Session` not always being initialised.

It is initialised in `rom.Session._init()`, which is only called by `Session.add()`, `.forget()`, `.get()`, `.flush()` and `.refresh()`.  
So in the scenario where a query with filters is the first thing executed on the session, before any of those operations, `.known` does not exist, hence the statement `isk = set(session.known.keys())` (added in 1dade8515f5efd5415f6e5e9e0f6bb1e5136694a) crashes with the above exception.

Is there any reason for not systematically running that `_init()` method in `__init__()`?

**Comment by josiahcarlson** [comment]
I'm sorry for taking so long to get back to you, I've been busy.

Thank you for the bug report, I've just released version 0.42.1 to address the bug. For why in the past `_init()` wasn't called from `__init__()`, I can't even remember my original reasons, as that code was written within the first 2 months of rom's release, more than 5 years ago.

Now fixed, thank you again.
