### ISSUE TITLE
Session caching problem - Existing attribute values of an entity are set to None

### ISSUE THREAD

**Issue by healiseu** [josiahcarlson/rom#125]
Hi, I have run a test on OneToMany relationship case. You can download my Jupyter Notebook file ( ROM - Testing One to Many Relationship.ipynb) for this test which is located at [my Microsoft Azure notebooks library][1]. JSON Datasets are also included in the same folder.

Regarding to the caching problem, I tried two different scenarios:

#### Session Cach Enabled
Models are created and populated from JSON datasets. You can execute a select-limit query to view 10 instances for each Company, Item entity types. So far so good, but then I tried to order the same 10 Items by price. It turns out that **you cannot use a select-limit-order_by combination**. The query is executed but the result set is not limited to 10 instances. 

_I want to ask more about ordering but I will reserve the space here for the caching problem and open  another issue about the ordering problem (see #126)._

So I tried a different way with list comprehension on tuples made with attribute values for each item.  But that raised an `AttributeError: 'NoneType' object has no attribute 'comp_id'`
Now further down if you run the code of fetching a single item with id=10 you will notice that when you render the output to a dictionary many attribute values **appear to be None**. But if you fetch the same item directly from Redis hash table you will see that these attributes have existing normal values.

This is a problem with the session cach, you can skip the error and avoid displaying Null values if you run the command `session.refresh_all(force=True)`. If we comment out this line and re-execute the cell that raised the `AttributeError` you will get a nice formatted tabular output and the `to_dict()` method will display all the values of the item.

#### Global Session Caching Disabled
This time I ran the notebook by commenting out the `util.use_null_session()` command at "Disable caching on a global basis section". Since we disabled session caching we have also to save each newly created object inside the populate loops (comment/uncomment lines appropriately there and make sure that the line `session.refresh_all(force=True)` is commented). Restart kernel and run all. There is no error and all the attribute values are displayed properly.

Also notice that because there is no caching `Item.get(10)` is executed three times and each time the address of the object that is created is different.

#### Trying to disable caching at a different point of notebook execution
That said I reversed to the first case with **caching enabled and no session refreshing**. I restarted the kernel, ran all and got to the point that you fetch a single item with id=10 three times. But this time I tried to disable caching by commenting out the `session.null_session=True`. Disabling caching at this point without executing `session.rollback()` prior to this, it is not going to fetch Item 10 each time with a different address. That makes me also to ask you what is the case that you need to execute separately rollback() and you do not include that inside the null_session method.

OK I am not sure if this behavior I described in this test is a bug, but it looks like one has to be extremely cautious when caching is enabled/disabled to avoid unexpected errors. Perhaps it's also a good idea to explain in the documentation with a few examples how Session methods that are related to caching work together.

I have also read again the documentation on `Session.commit()`. It says that it **forgets all known entities in the session**. Do you mean after expiration ? I think the reader is mislead here. It's definitely session.rollback() that has to be called to clear the cache of loaded entities (see also issue #124)

[1]: https://notebooks.azure.com/athanassios/libraries/redisrom

**Comment by josiahcarlson** [comment]
I've got a fix for this one too, the `Model.query.select()` call was polluting the session when it wasn't supposed to, by way of the `PrimaryKey` column decoding / loading of the data. This and the other bug should be fixed in 0.42.2 , which should be available soon. Thank you for the bug report.
