### ISSUE TITLE
Text Column strange behavior on order_by and filter operations

### ISSUE THREAD

**Issue by healiseu** [josiahcarlson/rom#128]
Hi, I wrote this simple ROM Class and a few instances to demonstrate my case

```python
class TestText(Model):
    txt_identity = Text(index=True, keygen=IDENTITY)
    txt_simple   = Text(index=True, keygen=SIMPLE)

txt1 = TestText(txt_identity='BLACK',  txt_simple='BLACK')
txt2 = TestText(txt_identity='BROWN',  txt_simple='BROWN')
txt3 = TestText(txt_identity='BRONZE', txt_simple='BRONZE')
txt4 = TestText(txt_identity='RED',    txt_simple='RED')
txt5 = TestText(txt_identity='BROWN',  txt_simple='BROWN')
txt6 = TestText(txt_identity='BLACK',  txt_simple='BLACK')
txt7 = TestText(txt_identity='BROWN',  txt_simple='BROWN')

session.commit()
```
The impossible task, thus the strange behavior, is to order/filter txt objects using either the Text(IDENTITY) column or the Text(SIMPLE) column. Let's start with txt_identity
```python
# Filtering
TestText.query.select('txt_identity', ff=_tuple_data_factory).filter(txt_identity='BROWN').all()
Out[19]: [('BROWN',), ('BROWN',), ('BROWN',)]

# Ordering
TestText.query.select('txt_identity', ff=_tuple_data_factory).order_by('txt_identity').all()
UserWarning: You are trying to order by a non-numeric column 'txt_identity'. Unless you have provided your own keygen or are using one of the sortable keygens: (SIMPLE, SIMPLE_CI,CASE_INSENSITIVE), this probably won't work the way you expect it to.'''
Out[20]: []
```
So with Text-IDENTITY column you can do filtering but order_by fails and the warning explains that I have to use SIMPLE keygen. Fine let's see how Text-SIMPLE works:
```python
#Ordering
TestText.query.select('txt_simple', ff=_tuple_data_factory).order_by('txt_simple').all()
Out[22]:  [('BLACK',), ('BLACK',), ('BRONZE',), ('BROWN',), ('BROWN',), ('BROWN',), ('RED',)]

# Filtering
TestText.query.select('txt_simple', ff=_tuple_data_factory).filter(txt_simple='BROWN').all()
Out[23]: []
```
Text column with SIMPLE keygen seems to work fine with order_by but it fails on filtering.
That means there is either a bug or from the user point of view it is not practical to define two Text column attributes in order to do filtering and/or order_by. 
What do you think ? I am currently using the Text(index=True, keygen=IDENTITY) to work with a simple enumerated type and I would like to order my class objects by such a type. Is there anything I can do in this case e.g. how exactly I can define and use a sortable keygen without loosing filtering ?

**Comment by josiahcarlson** [comment]
I am sorry, but I am currently on holiday and won't be able to give more
detail, but this question was asked before, and what is and is not possible
should be documented. Please see this issue, my comments, and related
documentation.

https://github.com/josiahcarlson/rom/issues/97

**Comment by healiseu** [comment]
OK the difference between the SIMPLE/SIMPLE_CI and the IDENTITY/IDENTITY_CI is indeed well documented at the columns Module but it escaped my attention. Nevertheless I had to look under the hood where Redis creates its structures to understand that IDENTITY* is based on SETs and SIMPLE* is based on ZSET ONLY and therefore you use the first for equality matching ONLY and the second for ordering ONLY. 
Now If I understand the logic on how to create indexes the case I have can be covered by having something like
```python
txt_identity_sorting = Text(index=True, keygen=IDENTITY, keygen2=????)
```
It's clear that I do not want to duplicate my data but use an additional zsort index on the enumerated type like the one defined in the SIMPLE keygen. So what's the best solution for this, do I use a keygen2 or do I define an IndexOnly column. By the way I am also a bit confused on the difference between keygen2 and IndexOnly.
Thanks for answering and wish you a nice relaxed time on your vacations

**Comment by josiahcarlson** [comment]
I believe I mentioned what rom uses each structure for in another of our
threads, and I know I mentioned somewhere out there (maybe not to you
directly) that rom itself was basically an expanded and applied version of
chapter 7 from my book.

Anyway, you can't pass `keygen` and `keygen2` at the same time. That
doesn't work. Never meant to. And at least right now, it is not possible to
order by the column data in the right way to combine both `SIMPLE` and
`IDENTITY` with a single index (I can fix it when I get home in 2 weeks).

The simplest method is to keep the sorting separate from the equality with
an `IndexOnly` column. Also remember, sorting only occurs on a (7 byte)
prefix when using `order_by` on string/text columns thau use
`SIMPLE`/`SIMPLE_CI` in rom.

As for `IndexOnly` and `keygen2`... `IndexOnly` is a fake column meant to
offer secondary+ indexes on columns with an existing index already. But
`keygen2` can be passed to most column types to provide an index on any
data in the model, even duplicating indexes (a waste, but possible). An
example: I will keep multiple `IndexOnly` columns that return the same data
(for a sort) under different conditions. Some conditions (and column names)
might be `just_created`, `needs_processing`, or
`requires_external_cleanup`. The data exists once, different columns give
different contexts obviously, and range queries are easy.

... which leads me to why this doesn't already exist. Long story short
(again, I am not at home, and won't be for another couple weeks, so can't
fix it now), querying over this data is fairly annoying, and I didn't want
to introduce more people to the ugly syntax, if I didn't have to. How ugly?
You have to pass `**{'column_name:<wanted_data>': (<start>, <end>)` to
query a range over an explicit matched string, and similar ugly to
`order_by`.

**Comment by healiseu** [comment]
I fully understand that trying to cover many generic query cases in ROM and at the same time maintaining a simple to use command line interface is not an easy task. Sorting and filtering are distinct operations and have to be treated separately so that they can be combined. But although this is true for the API logic, behind the scenes a memory/speed optimization can dictate a different approach....

**Comment by healiseu** [comment]
Update: 
```python
class TestText(Model):
    txt_simple_prefix = Text(index=True, keygen=SIMPLE, prefix=True
```
I have also tried to add the prefix index and then tested the `like` operator:
```python
TestText.query.like(txt_simple_prefix='BROWN').all()
```
And this also returns an empty result set. 
But documentation on columns Module says:
"_To each of those 3 index types, you can further add a prefix/suffix index_"
This is true, you can add the prefix but it is not functional.

**Comment by josiahcarlson** [comment]
In the process of writing tests for this before fixing it, I discovered that the `order_by` part already worked for all cases I was thinking that you might be interested in. Also, re-reading most of your messages above, I believe I have a keygen that should just work for the equality / order_by cases:

```
In [3]: def find_and_sort_keygen(data):
   ...:     r = rom.SIMPLE(data)
   ...:     r[data] = None
   ...:     return r
   ...: class RomTestText(rom.Model):
   ...:     txt_comp = rom.Text(index=True, keygen=find_and_sort_keygen)
   ...: 
   ...: txt1 = RomTestText(txt_comp='BLACK')
   ...: txt2 = RomTestText(txt_comp='BROWN')
   ...: txt3 = RomTestText(txt_comp='BRONZE')
   ...: txt4 = RomTestText(txt_comp='RED')
   ...: txt5 = RomTestText(txt_comp='BROWN')
   ...: txt6 = RomTestText(txt_comp='BLACK')
   ...: txt7 = RomTestText(txt_comp='BROWN')
   ...: 
   ...: rom.session.commit()
   ...: 
Out[3]: 14

In [4]: RomTestText.query.select('txt_comp').order_by('txt_comp').all()
/usr/local/bin/ipython:1: UserWarning: You are trying to order by a non-numeric column 'txt_comp'. Unless you have provided your own keygen or are using one of the sortable keygens: (SIMPLE, SIMPLE_CI, CASE_INSENSITIVE), this probably won't work the way you expect it to.
  #!/usr/local/bin/python3.6
Out[4]: 
[{'txt_comp': 'BLACK'},
 {'txt_comp': 'BLACK'},
 {'txt_comp': 'BRONZE'},
 {'txt_comp': 'BROWN'},
 {'txt_comp': 'BROWN'},
 {'txt_comp': 'BROWN'},
 {'txt_comp': 'RED'}]

In [5]: RomTestText.query.select('txt_comp').filter(txt_comp='BLACK').all()
Out[5]: [{'txt_comp': 'BLACK'}, {'txt_comp': 'BLACK'}]
```

This isn't optimal. It uses a set for the equality mapping and a sorted set for the ordering. But it does get you both features at the same time, on the same column. Is there other functionality you need from this, or is equality filtering + ordering sufficient?
