### ISSUE TITLE
redis.exceptions.ResponseError: unknown command 'EVAL'

### ISSUE THREAD

**Issue by kpchand** [josiahcarlson/rom#129]
Here is the traceback:

```
  File "/home/kaustubh/envs/rsenv/railsense/mods/ntes/commons.py", line 116, in create_cookie
    cookie.save()
  File "/home/kaustubh/envs/rsenv/lib/python3.5/site-packages/rom/model.py", line 462, in save
    self._last, new, full or self._new or force, is_new=self._new or force)
  File "/home/kaustubh/envs/rsenv/lib/python3.5/site-packages/rom/model.py", line 433, in _apply_changes
    delete)
  File "/home/kaustubh/envs/rsenv/lib/python3.5/site-packages/rom/model.py", line 828, in redis_writer_lua
    result = _redis_writer_lua(conn, [], [namespace, id] + data)
  File "/home/kaustubh/envs/rsenv/lib/python3.5/site-packages/rom/util.py", line 788, in call
    'EVAL', script, len(keys), *(keys + args))
  File "/home/kaustubh/envs/rsenv/lib/python3.5/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/kaustubh/envs/rsenv/lib/python3.5/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/home/kaustubh/envs/rsenv/lib/python3.5/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'EVAL'
```

**I am using redis version 3.0.6 and rom 0.40.2**

**Comment by josiahcarlson** [comment]
My apologies for not being more able to help directly now (I am on holiday
without access to a computer for another ~10 days, except to give advice on
where to look).

Looking at the exception, it would seem that your Redis does not have the
`EVAL` command. If your Redis does not have the `EVAL` command, then either
you are using a version of Redis prior to 2.6 (recent downgrade?), you have
renamed the `EVAL` command to something else in your Redis config with
`rename-command`, or you've recently upgraded rom from a version of rom
that didn't require Lua Scripting to one that now does (the switch happened
in rom 0.36.0,  May 2016).

Could you check if any one of those is the case?

**Comment by kpchand** [comment]
Thank you for replying and I apologize for bugging you during the holidays.
I am posting more information and if this is something which can be pointed out easily, then help me otherwise I will continue looking myself. 

I am using Redis 3.0.6 and Rom 0.40.2

```
> redis-server --version
> Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42
```

Here is the Redis configuration file. This doesn't have any rename command. This is the default one on an installation in Ubuntu 16.04.

```
daemonize yes
pidfile /var/run/redis/redis-server.pid
port 6379
tcp-backlog 511
bind 127.0.0.1
timeout 0
tcp-keepalive 0
loglevel notice
logfile /var/log/redis/redis-server.log
databases 16
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir /var/lib/redis
slave-serve-stale-data yes
slave-read-only yes
repl-diskless-sync no
repl-diskless-sync-delay 5
repl-disable-tcp-nodelay no
slave-priority 100
appendonly no
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-load-truncated yes
lua-time-limit 5000
slowlog-log-slower-than 10000
slowlog-max-len 128
latency-monitor-threshold 0
notify-keyspace-events ""
hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-entries 512
list-max-ziplist-value 64
set-max-intset-entries 512
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
hll-sparse-max-bytes 3000
activerehashing yes
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit slave 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
hz 10
aof-rewrite-incremental-fsync yes
```

**Comment by josiahcarlson** [comment]
Connect with a redis client and run `INFO`. That will tell you the actual
version you are running. Because if you are running 3.0.6, you are running
the only version of 3.0.6 that I know without Lua scripting.

**Comment by kpchand** [comment]
I did that and the version came out to be 2.4 which is different than what `redis-server --version` showed me.

However, this is a different issue. Thanks a lot for your help.

**Comment by josiahcarlson** [comment]
Happy to help.
