### ISSUE TITLE
Incompatibility with redis-py >= 3.0 - rom is broken as of 15 Nov 2018

### ISSUE THREAD

**Issue by stacywsmith** [josiahcarlson/rom#132]
redis-py 3.x was released on 15 Nov 2018 and has several [backwards-incompatible changes](https://github.com/andymccurdy/redis-py/blob/3.0.0/CHANGES#L2-L30).

Part of those changes are the [restructuring of class names](https://github.com/andymccurdy/redis-py/blob/3.0.0/CHANGES#L16-L19). This includes the [replacement of `BasePipeline` with `Pipeline`](https://github.com/andymccurdy/redis-py/commit/36a84fc9ac4e06a9b85ccc4e4eda426b387c7093#diff-085cbe85ef9bc2ad832d79163eb39172L3206).

This breaks rom with:
```
Traceback (most recent call last):
  File "./test_rom.py", line 1344, in test_weird
    RomTestSlaveServers(ip_address=ip).save()
  File "/Users/stacys/repos/rom/rom/model.py", line 486, in save
    self._last, new, full or self._new or force, is_new=self._new or force)
  File "/Users/stacys/repos/rom/rom/model.py", line 457, in _apply_changes
    delete)
  File "/Users/stacys/repos/rom/rom/model.py", line 872, in redis_writer_lua
    if isinstance(conn, client.BasePipeline):
AttributeError: 'module' object has no attribute 'BasePipeline'
```

**Comment by josiahcarlson** [comment]
Thank you again for the bug report and PR demonstrating the solution. See 0.43.4 release in PyPI or the 0.43.4 tag for the same stuff. Should now be fixed.

**Comment by stacywsmith** [comment]
Thanks for the quick merge and release!

**Comment by josiahcarlson** [comment]
No man, thank you for the quick notification of incompatibility. I should be paying better attention, and I appreciate the help. :)
