### ISSUE TITLE
No Attribute BasePipeline

### ISSUE THREAD

**Issue by robertbodley** [josiahcarlson/rom#134]
Hi,

I am using Python 3.6 and am getting the error
```
AttributeError: module 'redis.client' has no attribute 'BasePipeline'
```

which is coming from model.py line 872
```
    if isinstance(conn, client.BasePipeline):
        # we're in a pipelined write situation, don't parse the pipeline :P
        return
```

Please could you advise on how I can fix this.

Thank you!

**Comment by josiahcarlson** [comment]
Happy to have fixed this last week, maybe should have announced the fix. :)
