### ISSUE TITLE
Python 3.7+ support?

### ISSUE THREAD

**Issue by Frank5000** [josiahcarlson/rom#149]
Hi, was wondering if there were any plans in place to support 3.7/3.8/3.9?

Thanks

**Comment by josiahcarlson** [comment]
That is the plan, yes. I need to take the time to get a runtime set up for
them. Travis is about to go paid-only, so I need to set up a proper
docker-based testing setup before I can properly support it.

**Comment by josiahcarlson** [comment]
Actually, we already tested them before, I just forgot to update the setup.py. Let me do that now.

**Comment by josiahcarlson** [comment]
Give rom 1.0.3 a shot, and let me know if that doesn't work for you.
