### ISSUE TITLE
why not consider replace json by msgpack?

### ISSUE THREAD

**Issue by huangwei1024** [josiahcarlson/rom#53]
Lua support ``cmsgpack``.
msgpack better than json in efficiency, and msgpack could store more data type.
I replace  json by msgpack in my project, it's work good right now.
Any suggestions in this regard to consider it?

**Comment by josiahcarlson** [comment]
I have considered msgpack, and have rejected it for the reasons outlined in this pull request: https://github.com/josiahcarlson/rom/pull/51 .
