### ISSUE TITLE
How to expire an object?

### ISSUE THREAD

**Issue by jmmills** [josiahcarlson/rom#62]
I'm not seeing it in the documentation, so I'm assuming ROM doesn't have an opinion about key TTL, and thus no way to set a default (seems to never expire)?

From what I understand I could infer the key name and then set the ttl...

    obj = FluffyKitten.get_by(wiskers=4)
    rom.util.get_connection().expire(':'.join([obj.__class__, obj.id]))
    
Is there maybe an undocumented way to set this as a default in a model/class? If not, maybe a new feature via subclassing?

    class ForeverKitten(rom.Model):
        whiskers = rom.Integra()
    
    
    class EphemeralKitten(rom.Model):
    
        def ttl(self):
            x = super(EphemeralKitten, self).ttl()
            if x is None:
                return 60  # seconds
            else:
                return x

**Comment by josiahcarlson** [comment]
Please see the discussion on the partial pull request #47 and issue #40 for why I'm closing this.

If you have questions/comments that are not addressed there, please ask them here.

**Comment by jmmills** [comment]
Okay, I skimmed over the referenced issues. In my case it's a trivial to delete data as my application already has a scheduler in the mix. However, my knee jerk reaction is to avoid replication of functionality (Redis supports this already), the limitation being in this case that index data would become inconsistent as nothing is expiring items from it. Perhaps removing expired objects from the index when new objects are added to it?

**Comment by josiahcarlson** [comment]
It is possible to write a Lua script to perform a *slow* scan of the index that could incrementally clean up old index data, and it could be embedded inside the Lua script that currently handles all saving. But it would be slow. You would be better off just running `util.clean_old_index()` on your task server to handle the cleanup; it's faster and uses less resources. Run it as often as your needs dictate.

**Comment by jmmills** [comment]
Excellent, that's easy enough.

**Comment by josiahcarlson** [comment]
Also remember that `util.clean_old_index()` is a generator that yields its progress. To let it execute completely, ignoring the incremental progress report, `all(util.clean_old_index())` will do the job.
