### ISSUE TITLE
Scoped redis connection attribute for rom.Model

### ISSUE THREAD

**Issue by jmmills** [josiahcarlson/rom#64]
I may be off base here, but it would seem that rom.Model would benefit from a scoped connection attribute. There is no way from inside a object method to reference the objects redis connection, short of importing the util module.

It seems that this syntax would be nice, especially when you are using your rom Model simply for application persistence. 

Here is some code that explains it from a pub/sub standpoint where one may have a background job that accepts invitations:

    class KittenParty(rom.Model)
      name = rom.String()
      invitees = OneToMany('Kitten', column='party')
    
      def invite(self, name):
        self.redis.publish('party', '%s is invited to %s' % kitten.name)
        return self
    
    class Kitten(rom.Model):
      name = rom.String()
      party = rom.ManyToOne('KittenParty')
    
      def accept_invitation(self, id):
        self.party = KittenParty.get(id)
        self.redis.publish('party', '%s accepted invitation to %s' % (self.name, self.party.name))
        self.save()
        return self

**Comment by josiahcarlson** [comment]
This sort-of exists, but isn't really exposed, and arguably should be. I don't have time to do a release this week (for various reasons), but in the mean time, you could add the following to any model you want the `.redis` attribute to exist on, and it would work exactly as you describe:

```
@property
def redis(self):
    from rom.util import _connect
    return _connect(type(self))
```

For the sake of having something that will work now and in the future (if you don't want to maintain this particular property on your models), I'm probably going to give it a name of `_connection`, and it will basically be the above property.

**Comment by josiahcarlson** [comment]
This is now available as the `.connection` property on all models and entities when using rom 0.31.3 or later. :)
