### ISSUE TITLE
Wrapping Model.delete() 

### ISSUE THREAD

**Issue by peter-conalgo** [josiahcarlson/rom#70]
I need to do some of my own stuff before and/or after a model delete and save.

I've wrapped `Model.delete()` for this, however, I've had some trouble due to complexities involving the string `skip_on_delete_i_really_mean_it`. Doing the same on `save()` was straightforward.

Any ideas how to better handle this? I've seen a few approaches to this:
- various "signals" get emitted by the ORM ([blinker](https://pythonhosted.org/blinker/) is used for this sometimes)
- a full set of `pre_delete_hook()` / `post_delete_hook()` and such methods which are empty in base class, and called at just the right time. Easier to debug IMHO. Google App Engine's "ndb" does this.

**Comment by josiahcarlson** [comment]
I've been meaning to add `[before|after]_[insert|update|delete]` functionality for a while - I have been using SQLAlchemy's versions to spawn tasks for indexing into Redis for the last 5 1/2 years. I guess I'll just have to build it.

**Comment by josiahcarlson** [comment]
When subclassing `rom.Model`, adding methods defined with one or more or the following names:
`_before_insert`, `_before_update`, `_before_delete`, `_after_insert`, `_after_update`, `_after_delete`
... will cause them to be executed in the proper context. Exceptions in the `_before_*` methods will prevent the insert, update, or delete for that specific entity, and may prevent subsequent inserts/updates if using it as part of the `session.save()`. Exceptions in the `_after_*` methods may prevent subsequent saving if you are using `session.save()`, or if an exception occurs in any `_before_delete` or `_after_delete`, you may get inconsistent behavior if you are using the `on_delete='CASCADE'` (you'll definitely see the exception).

This is now available in 0.32.2.
