### ISSUE TITLE
How to filter by column != None?

### ISSUE THREAD

**Issue by peter-conalgo** [josiahcarlson/rom#71]
I have a `ManyToOne` column, and I'd like to know which rows have a value defined.

In SQLAlchemy, I'd do `Model.query.filter(Model.many21 != None)`, but ROM implemented what in SQLAlchemy would be `filter_by` using keyword arguments.

I tried doing: `Model.query.filter(Model.many21=(0,None))` which gave the right results.

If this type of query is possible, I'd suggest a constant in rom module like "rom.NotNull" or "rom.NotNone" or "rom.IS_DEFINED" and documenting clearly.

**Comment by josiahcarlson** [comment]
I'm calling it `rom.NOT_NULL`, and I really need to sit down and write a *lot* of docs for everything. :P

**Comment by josiahcarlson** [comment]
Minus the docs, this is now available in 0.32.2.
