### ISSUE TITLE
"values()" function for queries

### ISSUE THREAD

**Issue by peter-conalgo** [josiahcarlson/rom#75]
There are times I'd like to get just a few specific columns from a query set. This is the classic `values('column_name', 'col2', ...)` method on a query.

Naturally should be generator.

**Comment by peter-conalgo** [comment]
Actually... ideally it's a generator returning named tuple with column names.

I can live without `value()` feature, just need `values()`.

**Comment by josiahcarlson** [comment]
I won't be implementing this feature.

Efficient iteration over an arbitrary result set is a PITA, especially with the optimizations/features I already built for you in 0.32.0 - 0.32.2; see the `_iter_results()`, `_iter_all()`, `_iter_all_hscan()`, and `_iter_all_pkey()` methods in `rom/query.py`.

That said, you can build it with a combination of `Model.query.cached_result()` (for non-empty queries), the base key names from `Model._namespace` (check out how pkeys are generated in the `Model._pk` property), and pulling the data directly from the `Model._connection` via `Model._connection.hmget(pkey, colnames)` .
