### ISSUE TITLE
Default value for ManyToOne

### ISSUE THREAD

**Issue by peter-conalgo** [josiahcarlson/rom#76]
I'd like to have a ManyToOne column with a default and an `on_delete` of "set default".

But I think this means I'd need an instance of the ('One') model when I define the model.

Can I put a callable there?

**Comment by josiahcarlson** [comment]
You can always provide a function for `default=...` in column definitions, and "set default" was meant to be used with `default=...` here. Your function must either return an entity of the "One" side of the model, or `None` (assuming `required=False`) .

In the future, if you are just asking questions about rom, I would prefer if you would direct them to my email address. Please save the issue tracker for bugs and feature requests.
