### ISSUE TITLE
Support alternate JSON serializers: ujson, simplejson

### ISSUE THREAD

**Issue by peter-conalgo** [josiahcarlson/rom#77]
I'd like to use [uJSON](https://pypi.python.org/pypi/ujson) for performance critical cases, and sometime I need to use [Simple JSON](https://pypi.python.org/pypi/simplejson) when I need to handle monetary values correctly (ie. `Decimal`).

I often need to override the options for serializing/deserializing.

Maybe the interface to JSON column could be expanded to support these use cases.

Thanks!

**Comment by josiahcarlson** [comment]
Custom column types are easy to create. See the example below using simplejson.

```
import simplejson

class SimpleJson(rom.Column):
    # override this list of allowed input types as necessary (only for the top-level)
    _allowed = (dict, list, tuple)
    def _to_redis(self, value):
        return simplejson.dumps(value)
    def _from_redis(self, value):
        if isinstance(value, self._allowed):
            return value
        return simplejson.loads(value)
```

**Comment by peter-conalgo** [comment]
Very true, and without resorting to `ImportError` garbage, it's impossible to support all JSON packages. It's best if you don't try.

**Comment by josiahcarlson** [comment]
It's not even about the different json packages, it's that json is just a format, and the different libraries are just serializers. There is no particularly good reason to choose json for the columns over something like msgpack, thrift, protocol buffers, or even Python's pickle - depending on your needs.

Teach a man to fish, as they say. Now you (and anyone else) can have arbitrarily encoded columns if necessary, and it's documented ;)
