### ISSUE TITLE
I find other redis ORM ,It's have a lot of  features, but it's no longer maintenance ,Can this project integrate with the obsolete one? 

### ISSUE THREAD

**Issue by nooperpudd** [josiahcarlson/rom#78]
https://github.com/lsbardel/python-stdnet.
support asyncio , more data type field support.

I try want to maintain this project , but some bugs and issues I don't know how to fix.

So I think this project could adopt `stdnet` some features, and improve the rom.

**Comment by josiahcarlson** [comment]
If you can be specific about what features from python-stdnet you would like added, I can consider them one at a time.

**Comment by kishorpawar** [comment]
Hey, I was exploring redisco and python-stdnet too. What I feel lacking is self-reference (employee-manager relationship).

Could you please add this to your library?

Thanks a ton for such superb library.

**Comment by josiahcarlson** [comment]
Can you give code that shows what you would like to type to get what you want? And can you also describe the semantics of what you mean?

**Comment by kishorpawar** [comment]
Okay. First of all sorry :-( for delayed reply.


This is what I meant by self-reference.
```
class Employee(models.model):
    manager = models.ForeignKey('Employee')
```

This is how Django implements what I want.

> To create a recursive relationship – an object that has a many-to-one relationship with itself – use models.ForeignKey('self', on_delete=models.CASCADE).

Hope this clears.

**Comment by josiahcarlson** [comment]
This already works:
```
import rom

class RomTestRecursiveModel(rom.Model):
    manager = rom.ManyToOne('RomTestRecursiveModel', on_delete='set null')
    reports = rom.OneToMany('RomTestRecursiveModel')

a = RomTestRecursiveModel()
a.save()
b = RomTestRecursiveModel(manager=a)
b.save()
assert a == b.manager
assert a.reports == [b]
```

**Comment by josiahcarlson** [comment]
I'm going to close this issue because it's getting to be a general "feature request" thread. Those should be created individually and tracked individually. In the future, if someone has specific feature requests, I will respond to them individually.
