### ISSUE TITLE
feature request, expire support

### ISSUE THREAD

**Issue by aleks-mariusz** [josiahcarlson/rom#83]
It would be nice if there was an optional expire parameter that would cause all related data of a model to get cleaned up when expired, automatically by redis (vs us having to do something like add an 'age' parameter to the model and then manually set up a process to clean up model objects ourselves).

has this been considered, is it on the roadmap?

**Comment by josiahcarlson** [comment]
This has been brought up several times before, the most recent being #62. I explain the reasons why rom can't/won't support this in that bug, and in the bugs/PRs linked from there.
