### ISSUE TITLE
Does ROM support expiring objects?

### ISSUE THREAD

**Issue by jpassaro** [josiahcarlson/rom#87]
If not, would it make sense to add such a feature?

**Comment by josiahcarlson** [comment]
See the most recent issue regarding this: https://github.com/josiahcarlson/rom/issues/83

**Comment by jpassaro** [comment]
Ah, sorry I didn't spot that earlier, bit of a Github newb and didn't see the list of closed discussions. Thank you!

**Comment by jpassaro** [comment]
However given how often it seems you've had to answer the same question, maybe it would help to throw something in the docs? I searched the docs for any mention of redis expiration/ttl before posting this, perhaps others will too.

**Comment by josiahcarlson** [comment]
Just updated the docs to include the information, advice, and rationale. Thank you for the reports, and best regards :)
