### ISSUE TITLE
Subclassing existing ROM models

### ISSUE THREAD

**Issue by jpassaro** [josiahcarlson/rom#88]
Are there any hidden pitfalls to creating a subclass to an existing ROM model?

Use case for me is I'd like to store simulation data in a separate database, so that it can imitate the structure exactly but avoid conflicts with live data. E.G.:

```python
class Data(rom.Model):
    id = rom.PrimaryKey(indexed=True)
    data = rom.Integer()

class SimulatedData(Data):
    _conn = get_simulation_db()
```

Metaclass mechanics are a bit fuzzy to me, and the lack of explicit mention of deeper subclasses in the _ModelMetaclass makes me a little nervous. Even though the above code snippet runs without issue, I'd like to make sure there aren't any obvious traps I'm walking into.

**Comment by josiahcarlson** [comment]
There are no pitfalls to subclassing with rom, aside from needing to use a different name (of course). Everything else works as expected.

If you have further usage questions, please email me directly so I can keep the issue tracker for bugs and pull requests.

**Comment by jpassaro** [comment]
I ran into something weird when I tried a non-trivial example. There is an easy work-around that should be documented. Unfortunately I can't really raise this as an issue because I can't reproduce it reliably; @josiahcarlson if you think it worth pursuing, maybe you 

Base class defines id = rom.PrimaryKey(index=True)
Subclass defines only an alternative _conn attribute

My subclass raised the following error:

  File "/usr/local/lib/python2.7/site-packages/rom/__init__.py", line 202, in __new__
    raise ColumnError("Cannot have non-primary key named 'id' when no explicit PrimaryKey() is defined")
rom.exceptions.ColumnError: Cannot have non-primary key named 'id' when no explicit PrimaryKey() is defined

*Successful workaround*: redefining id in the subclass.

@josiahcarlson I'm sending more detailed debug information via email in case you want to pursue this. Since I have a workaround it seems like it wouldn't be high priority.

**Comment by josiahcarlson** [comment]
After discussing this offline, it ends up that @jpassaro works for my old company, and he ran into a hack that I did to bypass an intentional design decision in rom for the sake of an optimization.

Because I don't want folks accidentally breaking their data for the sake of speed (I know the implications, I can't explain them to everyone), I'm not going to describe it. I'll just say that if you use rom as designed, you shouldn't have issues subclassing.
