### ISSUE TITLE
Support for Redislite

### ISSUE THREAD

**Issue by prologic** [josiahcarlson/rom#89]
It would be really nice to have support for [Redislite](https://pypi.python.org/pypi/redislite)

Use-case: Use rom atop either Redis or Reidslite (*embedded*)

**Comment by josiahcarlson** [comment]
Have you tried it? Because according to my tests, RedisLite works fine:

```
>>> import rom
>>> from redislite import Redis
>>> rom.util.CONNECTION = Redis('/tmp/redis.rdb')
>>> class Foo(rom.Model):
...   bar = rom.Integer()
... 
>>> a = Foo(bar=1)
>>> a.save()
2
>>> a.id
1
>>> Foo.get(a.id)
<__main__.Foo object at 0x7f972de28ed0>
>>> del a
>>> rom.util.session
<rom.util.Session object at 0x7f972fbd5ef0>
>>> rom.util.session.rollback()
>>> Foo.get(1)
<__main__.Foo object at 0x7f972de28ed0>
>>> _.bar
1
>>> Foo.get(1).delete()
>>> Foo.get(1)
>>> 
```

Have you been experiencing any specific issues?

**Comment by prologic** [comment]
Ahh thanks! No I actually hadn't tried it (sorry!) -- I assumed it was more complicated than this :)

**Comment by josiahcarlson** [comment]
All right, closing the issue :)

**Comment by prologic** [comment]
Thanks :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
