### ISSUE TITLE
Substring-based full text search

### ISSUE THREAD

**Issue by yuvadm** [josiahcarlson/rom#91]
As far as I can tell none of the current full-text search options covers arbitrary substring searches. For example, the string `abcde fghi` should come up when searching for `cde`.

How hard would it be to implement this search strategy?

**Comment by josiahcarlson** [comment]
1. Redis already has arbitrary substring search available (depending on the context); it is pattern matching or prefix matching on a prefix index, or it is suffix matching on a suffix index
2. If you don't have a partial prefix in your pattern (the pattern starts with `?`, `*`, `+`, or `!`), and are using a `.like()` query, it will be very slow.

How do you use what is already there?

```
import rom

class mymodel(rom.Model):
    col = rom.String(keygen=rom.FULL_TEXT, prefix=True, suffix=True)


X = mymodel(col='this will have a prefix and suffix index, the prefix index offers pattern queries, and is case-insensitive')
X.save()

assert mymodel.query.like('*de*').first() is X # matches in[de]x and is slow
assert mymodel.query.startswith('pref').first() is X # matches [pref]ix and is pretty fast
assert mymodel.query.endswith('ffix').first() is X # matches su[ffix] and is also pretty fast
```
