### ISSUE TITLE
Model.query.filter not work!

### ISSUE THREAD

**Issue by summer1988** [josiahcarlson/rom#93]
I create a Model like this:
```
class Job(rom.model.Model):
    """Job for scheduler to handle"""

    name = rom.Text(index=True, keygen=rom.SIMPLE_CI, unique=True)
    status = rom.Json()
    state = rom.Text(default=JobState.CREATE.name, index=True, keygen=rom.SIMPLE_CI)
    src = rom.Text()
    cron_time = rom.Text()
    delay_del = rom.Integer(default=0)
    update_at = rom.Float(default=time.time(), index=True, keygen=rom.IDENTITY)
    expire_at = rom.Float(default=0, index=True, keygen=rom.IDENTITY)
```
but when I use `Job.query.filter(expire_at=0).execute()` it return nothing, Where am I wrong!

**Comment by josiahcarlson** [comment]
Remove the `keygen=` arguments to `update_at` and `expire_at`. There is a default keygen for "numeric" columns that works right; what you're doing right now is actually trying to use a string keygen on a numeric column, which is why it doesn't work.

Let me know if you have any issues.

**Comment by josiahcarlson** [comment]
Closing issue due to lack of response, and because this is an API use issue, not a bug with rom.
