### ISSUE TITLE
FULL_TEXT should be part of the `Query._check` as `lower()` candidates

### ISSUE THREAD

**Issue by slorg1** [josiahcarlson/rom#95]
Hi,

I am working with the `FULL_TEXT` `keygen` and while it works well to store the data, at query time, the input is not automatically lowercased.

In `Query._check` I see 
```
            if col._keygen.__name__ in ('SIMPLE_CI', 'CASE_INSENSITIVE', 'IDENTITY_CI'):
```

It seems like since `FULL_TEXT` is also case insensitive, it should be added to this collection.

Thank you.

**Comment by josiahcarlson** [comment]
You are right. Fixed in the just released version 0.37.1 . Thank you for the report!
