### ISSUE TITLE
FakeRedis/MockRedis

### ISSUE THREAD

**Issue by nabeelio** [josiahcarlson/rom#98]
I see that the disable lua has been removed... however, I guess that leaves it incompatible with FakeRedis/MockRedis for unit tests...

```
env/lib/python3.5/site-packages/rom/index.py:480:` in estimate_work_lua
    return _estimate_work_lua(conn, [index], args, force_eval=True)
env/lib/python3.5/site-packages/rom/util.py:796: in call
    return conn.execute_command(
env/lib/python3.5/site-packages/fakeredis.py:1588: in __getattr__
    (self.owner, name))
E   AttributeError: <fakeredis.FakeRedis object at 0x10c751c18>: does not have attribute 'execute_command'
```

Any suggestions?

**Comment by josiahcarlson** [comment]
Run a local or remote Redis server for your unittests. On the local side, if you're concerned about Redis bleeding out into the world, consider stuffing it into a Docker container. I know, not helpful, but I built rom to run on top of vanilla Redis, not to run on top of [not vanilla Redis].

The most recent rom has a few things that *require* the use of Lua scripting, and I am well past the point of having free time to maintain a second set of (inferior and incomplete) indexing/query operations. If running Redis and/or Docker is too much, you or your company could always purchase a support contract for restoring and maintaining disable Lua functionality going forward. For that, you can email me at the address attached to my github profile.
